apiVersion: v1
kind: Service
metadata:
  name: actix-app-service
spec:
  selector:
    deployment: "actix-app-${IMAGE_TAG}"
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30001 # Fixed port
  type: LoadBalancer
