apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: "react-app-${IMAGE_TAG}"
  template:
    metadata:
      labels:
        deployment: "react-app-${IMAGE_TAG}"
    spec:
      containers:
        - name: react-app-container
          imagePullPolicy: IfNotPresent # Fetch from local register
          image: "react-app:${IMAGE_TAG}" # Use your image name here
          ports:
            - containerPort: 80
          env:
            - name: ALT_GREETING
              valueFrom:
                configMapKeyRef:
                  name: the-map
                  key: altGreeting
            - name: ENABLE_RISKY
              valueFrom:
                configMapKeyRef:
                  name: the-map
                  key: enableRisky
