apiVersion: v1
kind: Service
metadata:
  name: react-app-service
spec:
  selector:
    deployment: "react-app-${IMAGE_TAG}"
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

