apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: trunk-based-development-demo
resources:
  - fe-deployment.yaml
  - be-deployment.yaml
  - fe-service.yaml
  - be-service.yaml
  - configMap.yaml
